---
title: "Méthode K-Means pour le cacao"
format: html
---
<script>
// == Imports ==
// Ici "zone" est un vecteur à 48 entités. Il a été créé pour séparer les zones de l'image prises dans des conditions différentes et éviter les seams 
// L'image totale va être découpée en 48 rasters et un k-means à 19 classes sera effectué sur les bandes de chaque raster.
// Après une comparaison avec la bande NIR, on va pouvoir obtenir

var zone = table.geometry();


// == Collections Landsat 8/9 ==

var L8 = ee.ImageCollection('LANDSAT/LC08/C02/T1_L2');
var L9 = ee.ImageCollection('LANDSAT/LC09/C02/T1_L2');

var col = L8.merge(L9);


// == Filtrage ==

var images = col
  .filterBounds(zone)
  .filterDate('2025-01-01', '2026-06-01')
  .filter(ee.Filter.lt('CLOUD_COVER', 30));

print('Nombre images :', images.size());


// == Masque de nuages ==

function mask(image) {

  var qa = image.select('QA_PIXEL');

  var mask = qa.bitwiseAnd(1 << 1).eq(0)
    .and(qa.bitwiseAnd(1 << 2).eq(0))
    .and(qa.bitwiseAnd(1 << 3).eq(0))
    .and(qa.bitwiseAnd(1 << 4).eq(0));

  return image.updateMask(mask);
}


// == Scale Factor USGS ==

function scale(image) {

  var optical = image.select([
    'SR_B2',
    'SR_B3',
    'SR_B4',
    'SR_B5',
    'SR_B6',
    'SR_B7'
  ])
  .multiply(0.0000275)
  .add(-0.2);

  return image.addBands(optical, null, true);
}


// == Mosaïque ==

var mosaic = images
  .map(mask)
  .map(scale)
  .median()
  .clip(zone);


// == Bandes K-means ==

var bands = [
  'SR_B2',
  'SR_B3',
  'SR_B4',
  'SR_B5',
  'SR_B6',
  'SR_B7'
];


// == Composition colorée RGB ==

Map.centerObject(table,8);


Map.addLayer(
  mosaic,
  {
    bands:[
      'SR_B4',
      'SR_B3',
      'SR_B2'
    ],
    min:0,
    max:0.3
  },
  'RGB'
);


Map.addLayer(
  table,
  {},
  'Polygones'
);


// == K-MEANS INDÉPENDANTS ==

var nb = table.size().getInfo();

print('Nombre polygones :', nb);


var list = table.toList(nb);



for (var i = 0; i < nb; i++) {


  var feature = ee.Feature(list.get(i));


  var geom = feature.geometry();


  // image locale

  var imgPoly = mosaic.clip(geom);



  // échantillonnage local

  var training = imgPoly
    .select(bands)
    .sample({

      region: geom,

      scale:30,

      numPixels:3000,

      geometries:false

    });



  // K-means propre au polygone

  var clusterer = ee.Clusterer
    .wekaKMeans(20)
    .train(training);



  // classification

  var clustered = imgPoly
    .select(bands)
    .cluster(clusterer)
    .toByte();



  // == Affichage des 48 rasters ==

  Map.addLayer(

    clustered,

    {

      min:0,

      max:19,

      palette:[

        'blue',
        'green',
        'yellow',
        'red',
        'purple',
        'orange',
        'cyan',
        'brown',
        'pink',
        'gray',
        'lime',
        'magenta',
        'teal',
        'navy',
        'white',
        'black',
        'gold',
        'coral',
        'violet',
        'darkgreen'

      ]

    },

    'KMEANS_' + (i+1),

    false

  );



  // == Export Google Drive ==


  Export.image.toDrive({

    image: clustered,

    description:
      'KMEANS_' + (i+1),

    folder:
      'GEE_Exports',

    fileNamePrefix:
      'KMEANS_' + (i+1),

    region:
      geom,

    scale:
      30,

    maxPixels:
      1e13

  });


}
</script>
